### ISSUE TITLE
Add option to omit leading zeros

### ISSUE THREAD

**Issue by Goldob** [Goldob/hh-mm-ss#2]
The following features are requested, along with test cases to support them:
- Add option not to add leading zeros in `fromMs()`, e.g. return `2:30` instead of `02:30` with input `150000`
- Make `toMs()` accept input without leading zeros

**Comment by davidwilde** [comment]
Hey @Goldob, Do you think that this would be an acceptable way of doing this:

```
TimeFormat.fromMs(3600000, 'h:mm:ss')   // '1:00:00'
```

I guess that in this case, it would also need

```
TimeFormat.fromMs(3600000, 'h:m:s')   // '1:00:00'
```

to work? Is that correct?

**Comment by Goldob** [comment]
I'm not sure. I was thinking about a similar solution, but I find it a bit unintuitive. I would rather replace `format` string with `options` object, containing optional `format` and `leadingzeros` (or similarily named) fields.

The new syntax would be `TimeFormat.fromMs(ms, [options])`.

However, to ensure backwards compatibilty, we should also accept format string as second argument (as before):

`TimeFormat.fromMs(ms, [format | options])`

## 

Example usage:

``` js
TimeFormat.fromMs(3600000, { format: 'hh:mm:ss', leadingzeros: false })  // '1:00:00'
TimeFormat.fromMs(3600000, 'hh:mm:ss') // '01:00:00'
```

## 

What do you think?

**Comment by davidwilde** [comment]
I think that my previous suggestion offers more flexibility. For example, you are able to display leading zeros on the minutes but not the hours with:

``` javascript
TimeFormat.fromS(60, 'h:mm:ss')     //  01:00
TimeFormat.fromS(3600, 'h:mm:ss')  // 1:00:00
```

I don't think that it is that unintuitive. I'd like to see how others have solved this

**Comment by Goldob** [comment]
Ok, I get it now. Still, your example is inconsistent with current version. The string format is supposed to provide **default** formatting, which is extended when needed - not the other way around.

`TimeFormat.fromS(60, 'h:mm:ss')` would return `0:01:00`.

In that context, `h:m:s` from two comments above also doesn't make sense - event with input zero it should output `0:00:00` (instead of `0:00` or whatever).

## 

Could this be changed and work as you proposed? Of course. The problem is, I don't want to change behavior of the module so freely. It is light enough for us to be able to keep it fully backwards compatible.
