### ISSUE TITLE
hh:mm support

### ISSUE THREAD

**Issue by alexcroox** [Goldob/hh-mm-ss#3]
It would be nice to support hh:mm format, I have a timing app where I don't want to show seconds ticking over as it's distracting

**Comment by YahiaElTai** [comment]
would you like some help with that ? should i do a PR and add it?

**Comment by Goldob** [comment]
Hi @YahiaElTai, thanks for stopping by! Any help will be appreciated, so feel free to do that.

**Comment by Goldob** [comment]
This feature has been implemented in PR #4 and added in [1.2.0](https://github.com/Goldob/hh-mm-ss/releases/tag/v1.2.0) release. Kudos to @YahiaElTai.
