### ISSUE TITLE
Format not working

### ISSUE THREAD

**Issue by alexcroox** [Goldob/hh-mm-ss#6]
I have the following:

```
export const formatSecondsToStopWatch = (seconds, displayFormat = 'hh:mm:ss') => {
  console.log('input', seconds)
  console.log('displayFormat', displayFormat)
  let test = timeFormat.fromS(seconds, displayFormat)
  console.log('output', test)
  return test
}

formatSecondsToStopWatch(2, 'hh:mm')
formatSecondsToStopWatch(2)
```

which outputs

```
input 2
stopwatch.js:59 displayFormat hh:mm
stopwatch.js:61 output 00:00:02
stopwatch.js:58 input 2
stopwatch.js:59 displayFormat hh:mm:ss
stopwatch.js:61 output 00:00:02
```

When I expecting the first output to be `00:00`

**Comment by alexcroox** [comment]
Created an example here: https://runkit.com/embed/jifu5u2r1j98

**Comment by Goldob** [comment]
Exerpt from `README.md`:

> Specified format constitutes a baseline for corresponding functions, but will be appropriately extended as needed. For example, `fromMs(9000, 'mm:ss')` will return `01:30`, yet `fromMs(9500, 'mm:ss')` will return `01:30.500` to account for the miliseconds part.

In other words, what you're seeing is actually intented behaviour. When you specify a format like `hh:mm`, that's only what the output will default to. However, if there's additional information in the input, like 2 seconds in your example, the resulting string will have appropriate format to capture it. If you don't want the seconds displayed, you need to round the `seconds` varibale to the nearest 60.
